language: objective-c # So that we get OS X build environment
install:
  - brew update
  - brew install caskroom/cask/brew-cask
  - while true; do sleep 300; echo x; done &
  - brew cask install mactex > /dev/null
  - kill $!
  - reset
script: rake
before_deploy:
  - mdkir cv
  - mv cv.pdf cv/cv.pdf
deploy:
  provider: s3
  access_key_id: AKIAJ4HSUQVUNZNKFJDQ
  secret_access_key:
    secure:
      hfgolkUogmvk12/sOidz5nS1jw2AIB+3YGRLfKQ2DmJjg/urXPllI3G3x7uXuSlu2GV3VIibj6jbnKVpXRk3JsHfa2n8c++gKSN/Wad6BTQh/IlAJ/is7U4gtvHYXY6VOduAZex82cyuEbfxH+QnModkSTqWdxRRMfilFW7rLw8=
  bucket: build.compevol.org
  local-dir: cv
  upload-dir: cv
  on:
    repo: armanbilge/cv
    branch: master
  skip_cleanup: true
notifications:
  email: false
