language: objective-c # So that we get OS X build environment
install:
  - brew install caskroom/cask/brew-cask
  - while true; do sleep 300; echo x; done &
  - brew cask install mactex > /dev/null
  - kill $!
  - PATH=/usr/texbin/:$PATH
  - while true; do sleep 300; echo x; done &
  - sudo tlmgr update --self --all > /dev/null
  - kill $!
script: rake
before_deploy:
  - mkdir cv
  - mv cv.pdf cv/cv.pdf
deploy:
  provider: s3
  access_key_id: AKIAIJMV4J6YK3H2JPTA
  secret_access_key:
    secure:
      b6QtZ14yQJKUNGZcrkfR84wRx0uHWK62Zwhn2NTiMDC1hWRCrTK1Vprr3MSpAiRLtuCx5DWhNYxCFGzDKElqp2rZb8utH7QReNBaLfJj2FQoM4+tZjeowg5opSt9kG7wDsaoPjeM2IiOSkhSB8/SDdxACPST/MAoXcxZ1uuyaXM=
  bucket: build.compevol.org
  local-dir: cv
  upload-dir: cv
  on:
    repo: armanbilge/cv
    branch: master
  skip_cleanup: true
notifications:
  email: false
