install:
  - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -zxvf install-tl-unx.tar.gz
  - cd install-tl-*
  - touch profile
  - ./install-tl --profile=profile
  - cd ..
  - PATH=/usr/local/texlive/2014/bin/i386-linux:$PATH; export PATH
script: rake
before_deploy:
  - mkdir cv
  - mv cv.pdf cv/cv.pdf
deploy:
  provider: s3
  access_key_id: AKIAIJMV4J6YK3H2JPTA
  secret_access_key:
    secure:
      b6QtZ14yQJKUNGZcrkfR84wRx0uHWK62Zwhn2NTiMDC1hWRCrTK1Vprr3MSpAiRLtuCx5DWhNYxCFGzDKElqp2rZb8utH7QReNBaLfJj2FQoM4+tZjeowg5opSt9kG7wDsaoPjeM2IiOSkhSB8/SDdxACPST/MAoXcxZ1uuyaXM=
  bucket: build.compevol.org
  local-dir: cv
  upload-dir: cv
  on:
    repo: armanbilge/cv
    branch: master
  skip_cleanup: true
notifications:
  email: false
